palette = "catppuccin_mocha"

format = """
[\ue0b2](lavender)\
$os\
$username\
$hostname\
$docker_context\
[\ue0b0](bg:pink fg:lavender)\
$directory\
[\ue0b0](fg:pink) \
([\ue0b2](fg:surface0)\
$git_branch\
$git_status\
$vcsh\
[\ue0b0 ](fg:surface0))\
$package\
$bun\
$c\
$cmake\
$deno\
$golang\
$gradle\
$java\
$kotlin\
$meson\
$nodejs\
$python\
$rust\
$zig\
$jobs\
$cmd_duration\
$status\
$line_break\
$conda\
$container\
$character\
"""

[bun]
style = "fg:rosewater"
symbol = " "
format = "[$symbol($version )]($style)"

[c]
style = "fg:blue"
symbol = " "
format = "[$symbol$version(-$name)]($style) "

[character]
success_symbol = "[](bold green)"
error_symbol = "[](bold red)"

[cmake]
style = "fg:blue"
symbol = " "
format = "[$symbol($version )]($style)"

[cmd_duration]
style = "fg:overlay0"
format = "[$duration]($style) "

[conda]
style = "fg:text"
format = "[$symbol$environment]($style) "
ignore_base = false

[container]
style = "fg:maroon"
symbol = ""
format = "[$symbol \\[$name\\]]($style) "

[deno]
style = "fg:green"
format = "[$symbol($version )]($style)"

[directory]
style = "bg:pink fg:base"
format = "[ $path ]($style)"

[directory.substitutions]
"/mnt/d/Projects" = " "
"~/Projects" = " "
"D:/Projects" = " "

[git_branch]
symbol = " "
style = "bg:surface0 fg:text"
format = "[ $symbol$branch ]($style)"

[git_status]
style = "bg:surface0 fg:text"
format = "[$all_status$ahead_behind ]($style)"

[golang]
style = "fg:teal"
symbol = "[](bold) "
format = "[$symbol($version )]($style)"

[gradle]
style = "fg:teal"
symbol = " "
format = "[$symbol($version )]($style)"

[hostname]
style = "bg:lavender fg:base"
format = "[@$hostname$ssh_symbol]($style)"
ssh_symbol = " 󰢹 "

[java]
style = "fg:maroon"
symbol = " "
format = "[$symbol($version )]($style)"

[jobs]
style = "fg:overlay0"

[kotlin]
style = "fg:mauve"
symbol = " "
format = "[$symbol($version )]($style)"

[meson]
style = "fg:blue"
symbol = "⬢ "
format = "[$symbol$project]($style) "

[nodejs]
style = "fg:green"
symbol = "󰎙 "
format = "[$symbol($version )]($style)"

[os]
disabled = false
style = "bg:lavender fg:base"

[os.symbols]
Arch = " "
Debian = " "
Fedora = " "
Ubuntu = " "
Windows = " "

[package]
style = "fg:yellow"
symbol = " "
format = "[$symbol$version]($style) "

[python]
style = "fg:yellow"
symbol = " "
format = "[${symbol}${pyenv_prefix}(${version} )(\\($virtualenv\\) )]($style)"

[rust]
style = "fg:peach"
symbol = " "
format = "[$symbol($version )]($style)"

[username]
style_user = "bg:lavender fg:base"
style_root = "bg:lavender fg:base"
format = "[$user]($style)"

[vcsh]
style = "bg:surface0 fg:text"
symbol = " "
format = "[$symbol$repo ]($style)"

[zig]
style = "fg:peach"
symbol = " "
format = "[$symbol($version )]($style)"

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
