---
name: Bump Flake Inputs
"on":
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  lockfile:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          logger: pretty
      - name: Nix Magic Cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Update Lockfile
        uses: DeterminateSystems/update-flake-lock@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pr-title: "chore(flake): update inputs"
      - name: Enable auto-merge
        shell: bash
        run: gh pr merge --auto --rebase "$PR_ID"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_ID: ${{ steps.update.outputs.pull-request-number }}
